<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Список контактов</title>
</head>
<body>
<div class="box">
    <div class="l1">
            <input type="text" placeholder="Найти" name="contactSerch" id="serch_input">
            <button id="serch_button">найти</button>
    </div>
    <div class="l2">
        <table>
            <tr>
                <td>ID</td>
                <td>Фамилия</td>
                <td>Имя</td>
                <td>Отчество</td>
            </tr>
            <?php foreach ($data as $row) { ?>
                <tr>
                    <td><?php echo $row['id'] ?></td>
                    <td><?php echo $row['lastName'] ?></td>
                    <td><?php echo $row['firstName'] ?></td>
                    <td><?php echo $row['middleName'] ?></td>
                </tr>
            <?php } ?>
        </table>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        var url=document.location.protocol+'//'+window.location.hostname;
        console.log(url);
        console.log(document.location.protocol);
        $('#serch_button').click(function () {
            var serchText = $('#serch_input').val();
            location = url+ '/index/serch/' + serchText;
        })
    });
</script>
</body>
</html>